### ISSUE TITLE
RStudio does not detect conda environments

### ISSUE THREAD

**Issue by psads-git** [rstudio/rstudio#10103]
As the title of this issue tells, my RStudio does not detect conda environments:

![conda](https://user-images.githubusercontent.com/75945439/142244741-52c86e79-a0e7-4f40-bf3d-86a301dc8e8a.png)

This is a follow up of this issue already reported:

https://github.com/rstudio/keras/issues/1291

The RStudio version I am using is the following:

```
RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-11) for Fedora release 35 (Thirty Five)
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.6 Chrome/87.0.4280.144 Safari/537.36
```

More information below:

```
$ find -L /opt ~ -type f -executable -name python |& grep -v 'find: .* Permission denied'
/home/x/.local/share/r-miniconda/envs/r-reticulate/bin/python
/home/x/.local/share/r-miniconda/pkgs/python-3.6.13-hb7a2778_2_cpython/bin/python
/home/x/.local/share/r-miniconda/pkgs/python-3.7.11-h12debd9_0/bin/python
/home/x/.local/share/r-miniconda/pkgs/python-3.9.5-h12debd9_4/bin/python
```

```
> Sys.getenv()
BASH_FUNC_ml%%          () { module ml "$@" }
BASH_FUNC_module%%      () { eval `/usr/bin/tclsh
                        /usr/share/Modules/libexec/modulecmd.tcl bash
                        "$@"`; _mlstatus=$?; return $_mlstatus }
BASH_FUNC_scl%%         () { if [ "$1" = "load" -o "$1" = "unload" ];
                        then eval "module $@"; else /usr/bin/scl "$@";
                        fi }
BASH_FUNC_which%%       () { ( alias; eval ${which_declare} ) |
                        /usr/bin/which --tty-only --read-alias
                        --read-functions --show-tilde --show-dot "$@" }
CLICOLOR_FORCE          1
CONDA_SHLVL             0
CVS_RSH                 ssh
DBUS_SESSION_BUS_ADDRESS
                        unix:path=/run/user/1000/bus
DEBUGINFOD_URLS         https://debuginfod.fedoraproject.org/
DESKTOP_SESSION         xfce
DISPLAY                 :0.0
EDITOR                  /usr/bin/nano
force_s3tc_enable       true
GDM_LANG                en_US.utf8
GDMSESSION              xfce
GIT_ASKPASS             rpostback-askpass
GRB_LICENSE_FILE        /home/paulus/gurobi500/gurobi.lic
GTK_IM_MODULE           ibus
GTK3_MODULES            xapp-gtk3-module
GUROBI_HOME             /home/paulus/gurobi500/linux64
HISTCONTROL             ignoredups
HISTSIZE                1000
HOME                    /home/x
HOSTNAME                fedora
IMSETTINGS_INTEGRATE_DESKTOP
                        yes
IMSETTINGS_MODULE       IBus
IPOPT_HOME              /home/paulus/ipopt
KDEDIRS                 /usr
LANG                    en_US.UTF-8
LD_LIBRARY_PATH         /usr/lib64/R/lib::/home/paulus/gurobi500/linux64/lib:/home/paulus/ipopt/lib/coin:/home/paulus/ipopt/lib/coin/ThirdParty:/home/paulus/solvers/Cbc-2.2.2/lib:/home/paulus/gambit/lib:/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/lib/jvm/jre/lib/server:/usr/java/packages/lib/amd64:/lib:/usr/lib::/home/paulus/gurobi500/linux64/lib:/home/paulus/ipopt/lib/coin:/home/paulus/ipopt/lib/coin/ThirdParty:/home/paulus/solvers/Cbc-2.2.2/lib:/home/paulus/gambit/lib
LESSOPEN                ||/usr/bin/lesspipe.sh %s
LN_S                    ln -s
LOADEDMODULES           
LOGNAME                 x
MAIL                    /var/spool/mail/x
MAKE                    make
MANPATH                 /usr/share/man:
MODULEPATH              /etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
MODULES_CMD             /usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE
                        LD_LIBRARY_PATH LD_PRELOAD
MODULESHOME             /usr/share/Modules
MOZ_GMP_PATH            /usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
MPLENGINE               tkAgg
PAGER                   /usr/bin/less
PANEL_GDK_CORE_DEVICE_EVENTS
                        0
PATH                    /usr/bin:/usr/share/Modules/bin:/usr/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/paulus/gurobi500/linux64/bin:/home/paulus/ipopt/bin:/home/x/bin:/home/paulus/scripts:/home/paulus/maple16/bin:/home/paulus/scilab/bin:/home/paulus/solvers/coin/bin:/home/paulus/gambit/bin:/usr/local/MATLAB/R2010b/bin:/home/x/.local/bin:/usr/libexec/rstudio/bin/postback
PSTILL_PATH             /home/paulus/pstill_dist
PWD                     /home/x
PYTHONIOENCODING        utf-8
QT_IM_MODULE            ibus
QT_QPA_PLATFORM         xcb
R_BROWSER               /usr/bin/xdg-open
R_BZIPCMD               /usr/bin/bzip2
R_DOC_DIR               /usr/share/doc/R
R_GZIPCMD               /usr/bin/gzip
R_HOME                  /usr/lib64/R
R_INCLUDE_DIR           /usr/include/R
R_LIBS_SITE             /usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib64/R/library:/usr/share/R/library
R_LIBS_USER             ~/R/x86_64-redhat-linux-gnu-library/4.1
R_PAPERSIZE             a4
R_PDFVIEWER             /usr/bin/xdg-open
R_PLATFORM              x86_64-redhat-linux-gnu
R_PRINTCMD              lpr
R_RD4PDF                times,inconsolata,hyper
R_SESSION_TMPDIR        /tmp/RtmpMPDRmc
R_SHARE_DIR             /usr/share/R
R_STRIP_SHARED_LIB      strip --strip-unneeded
R_STRIP_STATIC_LIB      strip --strip-debug
R_SYSTEM_ABI            linux,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD           /usr/bin/texi2dvi
R_UNZIPCMD              /usr/bin/unzip
R_ZIPCMD                /usr/bin/zip
RETICULATE_PYTHON       /usr/bin/python
RMARKDOWN_MATHJAX_PATH
                        /usr/libexec/rstudio/resources/mathjax-27
RS_PPM_FD_READ          80
RS_PPM_FD_WRITE         84
RS_RPOSTBACK_PATH       /usr/libexec/rstudio/bin/rpostback
RS_SHARED_SECRET        1852392633971594866264201463
RSTUDIO                 1
RSTUDIO_CONSOLE_COLOR   256
RSTUDIO_CONSOLE_WIDTH   82
RSTUDIO_PANDOC          /usr/libexec/rstudio/bin/pandoc
RSTUDIO_PROGRAM_MODE    desktop
RSTUDIO_SESSION_PORT    31809
RSTUDIO_USER_IDENTITY   x
RSTUDIO_WINUTILS        bin/winutils
SED                     /usr/bin/sed
SESSION_MANAGER         local/unix:@/tmp/.ICE-unix/2401,unix/unix:/tmp/.ICE-unix/2401
SHELL                   /bin/bash
SHLVL                   0
SSH_AGENT_PID           2509
SSH_ASKPASS             /usr/libexec/openssh/gnome-ssh-askpass
SSH_AUTH_SOCK           /tmp/ssh-XXXXXXQb1UYl/agent.2401
TAR                     /usr/bin/gtar
TERM                    xterm-256color
USER                    x
which_declare           declare -f
XAUTHORITY              /run/lightdm/x/xauthority
XDG_CONFIG_DIRS         /etc/xdg
XDG_CURRENT_DESKTOP     XFCE
XDG_DATA_DIRS           /home/x/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
XDG_GREETER_DATA_DIR    /var/lib/lightdm-data/x
XDG_MENU_PREFIX         xfce-
XDG_RUNTIME_DIR         /run/user/1000
XDG_SEAT                seat0
XDG_SEAT_PATH           /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS       user
XDG_SESSION_DESKTOP     xfce
XDG_SESSION_ID          2
XDG_SESSION_PATH        /org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE        x11
XDG_VTNR                1
XMODIFIERS              @im=ibus
> write(Sys.getenv(), file="/tmp/lixo.txt") 
> 
```

**Comment by kevinushey** [comment]
What is the output of the following for you?

```
.rs.python.findCondaBinary()
.rs.python.findPythonCondaEnvironments()
```

**Comment by psads-git** [comment]
Thanks, Kevin. The requested output is below:

```
> .rs.python.findCondaBinary()
           conda 
"/usr/bin/conda" 
> .rs.python.findPythonCondaEnvironments()
list()
Warning message:
In system2(conda, args, stdout = TRUE, stderr = FALSE) :
  running command ''/usr/bin/conda' env list --json --quiet 2>/dev/null' had status 1
> 
```

**Comment by kevinushey** [comment]
What happens if you try to run that equivalent command from a terminal?

```
/usr/bin/conda env list --json --quiet
```

**Comment by psads-git** [comment]
Thanks, Kevin:

```
$ /usr/bin/conda env list --json --quiet
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/conda/_vendor/toolz/__init__.py", line 28, in <module>
    from cytoolz import __version__ as cytoolz_version
  File "/usr/lib64/python3.10/site-packages/cytoolz/__init__.py", line 3, in <module>
    from .functoolz import *
  File "cytoolz/functoolz.pyx", line 9, in init cytoolz.functoolz
  File "/usr/lib64/python3.10/site-packages/cytoolz/_signatures.py", line 1, in <module>
    from toolz._signatures import *
ModuleNotFoundError: No module named 'toolz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/conda", line 33, in <module>
    sys.exit(load_entry_point('conda==4.10.3', 'console_scripts', 'conda')())
  File "/usr/lib/python3.10/site-packages/conda/cli/main.py", line 151, in main
    from ..exceptions import conda_exception_handler
  File "/usr/lib/python3.10/site-packages/conda/exceptions.py", line 22, in <module>
    from ._vendor.toolz import groupby
  File "/usr/lib/python3.10/site-packages/conda/_vendor/toolz/__init__.py", line 35, in <module>
    from .itertoolz import *
ModuleNotFoundError: No module named 'conda._vendor.toolz.itertoolz'
$ 
```

**Comment by kevinushey** [comment]
Not sure what to say beyond it sounds like something is borked in your system Conda installation...

**Comment by psads-git** [comment]
The reported problem is now fixed, after having reinstalled `python3-toolz`. Thanks, Kevin, for your help!

**Comment by kevinushey** [comment]
Thanks! We could certainly do better in reporting the error here, though.

**Comment by psads-git** [comment]
From running the command you suggested to me, Kevin, the error was:

`
ModuleNotFoundError: No module named 'toolz'
`
So, I tried to reinstall `python3-toolz`, that fixed the problem!

**Comment by mikebessuille** [comment]
Sounds like the improvement tracked in this ticket is to improve our error message in this case.

**Comment by kevinushey** [comment]
To confirm, my proposal here would be to catch and report errors here more properly:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionPythonEnvironments.R#L635-L639

In particular, we should check the status code output from `system2()` to confirm that things succeeded, and report an error (either via UI or just in the R console) so the user has an inkling of what went wrong.,

**Comment by jgutman** [comment]
The conda error message will display in the R console with this fix. If we wanted the error to also display in the UI (like in a dialog box that pops up) we'd have to address this #10443

**Comment by timtmok** [comment]
Verified in RStudio 2022.06.0-daily+60

**Comment by ozak** [comment]
I have the same issue with Version 2023.12.1+402 (2023.12.1+402). If I execute

<img width="322" alt="image" src="https://github.com/rstudio/rstudio/assets/650534/ebb18eed-6ba4-4819-9e4d-ddc1fb6d3e9a">

once I execute 

```r
library(reticulate)
use_condaenv(condaenv = conda_list()[[2]][3])
```
<img width="332" alt="image" src="https://github.com/rstudio/rstudio/assets/650534/e3872bf3-e700-4593-8c9e-52b64ac014ef">

etc. I tried changing my path in `.Renviron` but that did not work. I also checked and 

```zsh
conda env list --json --quiet
```
works and I do have `toolz` installed.

Not sure how to proceed. Any other ideas?

**Comment by kevinushey** [comment]
@ozak RStudio doesn't support automatic detection of Miniforge environments; I've pushed a change to help support that in the next release.

**Comment by ozak** [comment]
Thanks @kevinushey. Any suggestions on how to deal ith it in the meantime? I'd like to be able to `knitr` on my new laptop, but now I am stuck.

**Comment by kevinushey** [comment]
Can you install Miniconda instead of Miniforge?

**Comment by ozak** [comment]
Since I use mamba, the [recommended install](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html) is with `Miniforge`.  I could try to install `Miniconda` and copy the environment, but I'd rather not waste space in my drive. I may just wait for the update.

It is weird that `reticulate` can find it and use it without any issues, but Rstudio fails. Is it looking at fixed locations instead of trying to infer locations? Is there a way to force a $PATH?

**Comment by nolanjj** [comment]
> @ozak RStudio doesn't support automatic detection of Miniforge environments; I've pushed a change to help support that in the next release.
> 
> @ ozak RStudio 不支持 Miniforge 环境的自动检测; 我已经推出了一个更改来帮助在下一个版本中支持这一点。

Hi，Does the latest version Rstudio can detect miniforge now. I install the latest version Rstudio.
But still did not show miniforge
![image](https://github.com/user-attachments/assets/51e28cb9-6525-4539-8925-df5e955ba9ed)

I have install miniforge in my win10
![image](https://github.com/user-attachments/assets/937fd275-fbb9-40d2-aad6-6ac91941c2cb)

**Comment by ronblum** [comment]
@nolanjj Which version of RStudio are you using?

**Comment by nolanjj** [comment]
> @nolanjj Which version of RStudio are you using?
![image](https://github.com/user-attachments/assets/b8b5edad-c615-405f-a605-b74a98942f98)

**Comment by Sa-ku-mo** [comment]
In my case, it detected base but no envs in 2024.9.0.375.
And it says error occurred attempting to load that (in env, 4.4.1) version of R

**Comment by petecarswell** [comment]
I added the root folder my conda install to the path and it then was able to find it.
