### ISSUE TITLE
Supporting building GWT with newer JDKs (e.g. 18)

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#11242]
```
     [java] Compiling module org.rstudio.studio.RStudio
     [java]    Computing all possible rebind results for 'org.rstudio.studio.client.RStudioGinjector'
     [java]       Rebinding org.rstudio.studio.client.RStudioGinjector
     [java]          Invoking generator com.google.gwt.inject.rebind.GinjectorGenerator
     [java]             [ERROR] Generator 'com.google.gwt.inject.rebind.GinjectorGenerator' threw an exception while rebinding 'org.rstudio.studio.client.RStudioGinjector'
     [java] com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
     [java] 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
     [java] 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
     [java] 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
     [java] 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:507)
     [java] 	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:159)
     [java] 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
     [java] 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
     [java] 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:95)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:72)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:62)
     [java] 	at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:74)
     [java] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
     [java] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
     [java] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
     [java] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
     [java] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
     [java] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
     [java] 	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
     [java] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:76)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
     [java] 	at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:49)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
     [java] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
     [java] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
     [java] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
     [java] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
     [java] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
     [java] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
     [java] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:243)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:132)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:110)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:113)
     [java] Caused by: java.lang.ExceptionInInitializerError
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
     [java] 	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
     [java] 	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
     [java] 	at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:207)
     [java] 	at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:53)
     [java] 	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:153)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:89)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
     [java] 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
     [java] 	... 68 more
     [java] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6b12e224
     [java] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
     [java] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
     [java] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
     [java] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
     [java] 	at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
     [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
     [java] 	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
     [java] 	... 82 more
     [java]    [ERROR] Errors in 'org/rstudio/studio/client/RStudioGinjector.java'
     [java]       [ERROR] Line 357: Failed to resolve 'org.rstudio.studio.client.RStudioGinjector' via deferred binding
```

openjdk18-18.0.1+10.1

**Comment by gtritchie** [comment]
The GWT project requires JDK11 or 8. It won't build with newer JDKs (not 100% sure about 14, that might work, but 17 and above definitely do not).

**Comment by yurivict** [comment]
I found that Java 12 also works.

**Comment by gtritchie** [comment]
Retitled this to track supporting GWT builds with newer JDKs. I haven't investigated to see how feasible this is yet, but it would definitely be nice.

**Comment by gtritchie** [comment]
I'm working on upgrading RStudio to GWT 2.10.0, however, that alone won't enable building with anything above JDK 11.

RStudio extensively employs the [gin dependency injection framework](https://github.com/gwtplus/google-gin), and it doesn't work with JDK 17 (or anything above JDK 11, I believe).

I'll investigate that further once I've completed the GWT upgrade but it may prove intractable.

**Comment by gtritchie** [comment]
There's nothing specific to test here other than via general product usage. Closing.
