### ISSUE TITLE
Rstudio crashes with `gert::git_clone()` in the console, but not in the Terminal, on Ubuntu 22.04

### ISSUE THREAD

**Issue by statnmap** [rstudio/rstudio#12097]
### System details

    RStudio Edition : Desktop. 
    RStudio Version : Tested on 2022.07.1, 2022.07.2 and 2022.11.0 Build 240
    OS Version      :  Ubuntu 22.04.1 LTS
    R Version       :  R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem
```r
gert::git_clone(
  url = "https://github.com/ThinkR-open/fusen",
  path = tempfile("gert")
)
```

### Describe the problem in detail

When I try to clone a project using {gert} while running the above lines of code in the Console, RStudio crashes.
I think it is RStudio related because when I run it in the RStudio Terminal, it works properly.

_In the console_  
![gert_crash_1 9 0](https://user-images.githubusercontent.com/21193866/193861377-1e0341cd-15c1-4ed1-b6c7-88de4fdf3a83.png)

_In the terminal_  
![image](https://user-images.githubusercontent.com/21193866/193861600-6eea3618-e426-4e79-b76a-649abf47273a.png)

I tested different version of {gert}: 1.9.0, 1.8.0, on CRAN or from GitHub, even binaries on RSPM
No difference.

```r
> library(credentials)
Found git version 2.34.1
Supported HTTPS credential helpers: cache, store
Found OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
Default SSH key: /home/srochett/.ssh/id_rsa
> library(gert)
Linking to libgit2 v1.4.2, ssh support: YES
Global config: /home/srochett/.gitconfig
Default user: StatnMap <sebastien@thinkr.fr>
```

The crash appears when calling the C function as you may see in the debug window in the first screenshot.
```r
repo <- .Call(R_git_repository_clone, url, path, branch, 
    key_cb, cred_cb, bare, mirror, verbose)
```

I tested on RStudio versions: 2022.07.1, 2022.07.2 and 2022.11.0 Build 240

My Ubuntu 22.04.1 LTS is a fresh install. The computer is a new one.

### Describe the behavior you expected

I expect RStudio to not crash in this case. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9708595/diagnostics-report.txt)

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks! It's definitely crashing in `gert`...

```
Thread 1 "rsession" received signal SIGSEGV, Segmentation fault.
0x00007fb9def750e1 in asn1_item_embed_d2i () from /home/srochett/R/x86_64-pc-linux-gnu-library/4.2/gert/libs/gert.so
#0  0x00007fb9def750e1 in asn1_item_embed_d2i ()
   from /home/srochett/R/x86_64-pc-linux-gnu-library/4.2/gert/libs/gert.so
#1  0x00007fb9def7614d in ASN1_item_ex_d2i ()
   from /home/srochett/R/x86_64-pc-linux-gnu-library/4.2/gert/libs/gert.so
< ... >
```

It's surprising that you would see the crash within RStudio but not R in this case, though. Can you think of anything else that might be different between your RStudio instance and a terminal R instance?

**Comment by romainfrancois** [comment]
cc @jeroen

**Comment by jeroen** [comment]
Can you try installing gert using system libgit2?

```
Sys.setenv(USE_SYSTEM_LIBGIT2=1)
install.packages("gert", repos = "https://cran.r-project.org")
```

**Comment by statnmap** [comment]
This is working with version v1.1.0 for "libgit2", instead of "v1.4.2" in the previous tests

```r
remove.packages('gert')
#=> restart R
Sys.setenv(USE_SYSTEM_LIBGIT2=1)
install.packages("gert", repos = "https://cran.r-project.org")
# Found pkg-config cflags and libs!
#   Using PKG_CFLAGS=
#   Using PKG_LIBS=-lgit2
# Configuration OK!
#=> restart R

# > library(credentials)
# Found git version 2.34.1
# Supported HTTPS credential helpers: cache, store
# Found OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
# Default SSH key: /home/srochett/.ssh/id_rsa
# > library(gert)
# Linking to libgit2 v1.1.0, ssh support: YES
# Global config: /home/srochett/.gitconfig
# Default user: StatnMap <sebastien@thinkr.fr>
```

**Comment by statnmap** [comment]
Indeed, if I install from source, it works.  If I install from RSPM, it fails

_source_  
```r
> Sys.getenv("USE_SYSTEM_LIBGIT2")
[1] ""

> install.packages("gert", repos = "https://cran.r-project.org")
Installation du package dans ‘/home/srochett/R/x86_64-pc-linux-gnu-library/4.2’
(car ‘lib’ n'est pas spécifié)
essai de l'URL 'https://cran.r-project.org/src/contrib/gert_1.9.0.tar.gz'
Content type 'application/x-gzip' length 121010 bytes (118 KB)
==================================================
downloaded 118 KB

* installing *source* package ‘gert’ ...
** package ‘gert’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
Found OpenSSL3
Using static libgit2 for Linux x86_64
Using PKG_CFLAGS=-DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include
Using PKG_LIBS=-L/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/lib -lgit2 -lrt -lpthread -lssh2 -lssl -lcrypto -ldl
Configuration OK!
** libs
rm -f gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c branch.c -o branch.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c clone.c -o clone.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c commit.c -o commit.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c config.c -o config.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c conflicts.c -o conflicts.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c files.c -o files.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c init.c -o init.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c merge.c -o merge.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c rebase.c -o rebase.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c stash.c -o stash.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c submodules.c -o submodules.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c tag.c -o tag.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c utils.c -o utils.o
gcc -I"/usr/share/R/include" -DNDEBUG -DSTATIC_LIBGIT2 -I/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/include -DR_NO_REMAP -DSTRICT_R_HEADERS    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-wSz8CH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c version.c -o version.o
gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o gert.so branch.o clone.o commit.o config.o conflicts.o files.o init.o merge.o rebase.o stash.o submodules.o tag.o utils.o version.o -L/tmp/RtmpiUbQcf/R.INSTALL11ee12e3d5e52/gert/libgit2-1.4.2-x86_64_linux/lib -lgit2 -lrt -lpthread -lssh2 -lssl -lcrypto -ldl -L/usr/lib/R/lib -lR
installing to /home/srochett/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-gert/00new/gert/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (gert)

Les packages source téléchargés sont dans
	‘/tmp/Rtmpy5CRR0/downloaded_packages’

Restarting R session...


> library(credentials)
Found git version 2.34.1
Supported HTTPS credential helpers: cache, store
Found OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
Default SSH key: /home/srochett/.ssh/id_rsa
> library(gert)
Linking to libgit2 v1.4.2, ssh support: YES
Global config: /home/srochett/.gitconfig
Default user: StatnMap <sebastien@thinkr.fr>
> gert::git_clone(
+   url = "https://github.com/ThinkR-open/fusen",
+   path = tempfile("gert")
+ )
Transferred 4759 of 4759 objects...done!
Checked out 104 of 104 commits... done!
```

_rspm_
```r

install.packages("gert", repos = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest")
```
=> Fails

**Comment by kevinushey** [comment]
To confirm though:

> I tested different version of {gert}: 1.9.0, 1.8.0, on CRAN or from GitHub, even binaries on RSPM

Are you saying that you also see this issue when installing the package from sources on CRAN (not RSPM)? Or does it depend on whether you're using the system libgit2 library?

**Comment by jeroen** [comment]
@statnmap ok yes that was expected. The RSPM binaries were built before I deployed the fix in libgit2.

I have submitted a new version of gert to CRAN, so once rspm has built the new binaries in a few days, I think this problem should be resolved.

**Comment by romainfrancois** [comment]
Thanks. I guess that means we can close this issue.

**Comment by kevinushey** [comment]
Thanks @jeroen!

**Comment by statnmap** [comment]
Thanks @jeroen 
I was using `"https://cloud.r-project.org"` as default repos, which redirects to the nearest mirror.  
I guess the fix was not fully disseminated among mirrors?

It now works with all:
```r
install.packages("gert", repos = "https://cran.r-project.org")
install.packages("gert", repos = "https://cran.rstudio.com")
install.packages("gert", repos = "https://cloud.r-project.org")
```
But not with RSPM.
```r
install.packages("gert", repos = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest")
```
I'll wait before installing again from RSPM.
Thanks. This solves my current needs.

**Comment by jeroen** [comment]
It takes a few days for RSPM to get updated. Once gert 1.9.1 is on RSPM, it should work.
