### ISSUE TITLE
RStudio failing to boot Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by NatJWalker-Hale** [rstudio/rstudio#12613]
### System details

    RStudio Edition : Desktop
    RStudio Version : rstudio-2022.12.0-353
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : 4.2.1

### Steps to reproduce the problem

Install rstudio:
`sudo dpkg -i rstudio-2022.12.0-353-amd64.deb`

attempt boot:
`rstudio`

attempt boot sudo:
`sudo rstudio --no-sandbox`

### Describe the problem in detail

both boot commands fail. The former returns the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/nat/.config/RStudio/desktop.ini'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at c.append (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:255841)
    at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:255355)
    at e.exports (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:254974)
    at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:46571)
    at 7723 (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:48031)
    at __webpack_require__ (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:166352)
```
Although I'm not sure if this is the relevant js, my current `node -v` returns `v18.13.0`.

The second command opens a blank new application window, with no interface, and returns the much longer error string:

```
[9270:0123/130011.410754:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130011.410798:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[9302:0123/130011.444246:ERROR:gl_surface_glx.cc(432)] Could not open X11 connection.
[9302:0123/130011.444350:ERROR:gl_ozone_glx.cc(29)] GLSurfaceGLX::InitializeOneOff failed.
[9302:0123/130011.445614:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[9270:0123/130011.631129:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130011.748985:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[9384:0123/130011.757751:ERROR:gl_surface_glx.cc(432)] Could not open X11 connection.
[9384:0123/130011.757827:ERROR:gl_ozone_glx.cc(29)] GLSurfaceGLX::InitializeOneOff failed.
[9384:0123/130011.758843:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[9399:0123/130011.767322:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[9399:0123/130011.767383:ERROR:angle_platform_impl.cc(43)] Display.cpp:977 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[9399:0123/130011.767425:ERROR:gl_surface_egl.cc(852)] EGL Driver message (Critical) eglInitialize: Not initialized.
[9399:0123/130011.767453:ERROR:gl_surface_egl.cc(1489)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[9399:0123/130011.767483:ERROR:gl_ozone_egl.cc(21)] GLSurfaceEGL::InitializeOneOff failed.
[9399:0123/130011.768661:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[9406:0123/130011.773995:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[9406:0123/130011.775306:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 54525955
[9270:0123/130013.173158:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.344831:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.363649:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.486719:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.606713:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.655751:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.674287:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.730797:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[9270:0123/130013.965535:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```
Not sure what this implies about dependencies, but xorg, xauth etc. are all latest versions. I am using Nvidia driver 525, but the issue also persists with Nouveau display drivers.

### Describe the behavior you expected

Correct boot of rstudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by vkerchberger** [comment]
FWIW: I had a very similar issue & error codes after upgrading from Ubuntu 20 to 22.04. 
 
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: EACCES: permission denied, open '/home/kerchbve/.config/RStudio/desktop.ini'
>     at Object.openSync (node:fs:594:3)
>     at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
>     at readFileSync (node:fs:462:35)
>     at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
>     at c.append (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183934)
>     at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183448)
>     at e.exports (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183067)
>     at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:48863)
>     at 7723 (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:50323)
>     at __webpack_require__ (/usr/lib/rstudio/resources/app/.webpack/main/index.js:17:173823)

I was able to resolve it by clearing my RStudio preferences from the previous build -- moved them to backup directories as suggested by this link: [Resetting RStudio Desktop's State](https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State). 🤷

`mv ~/.local/share/rstudio ~/.local/share/rstudio-backup`
`mv ~/.config/rstudio/ ~/backup-rstudio`

**Comment by kevinushey** [comment]
> Error: EACCES: permission denied, open '/home/kerchbve/.config/RStudio/desktop.ini'

Somehow, permissions on your RStudio configuration folder changed such that your own user account could no longer access it. Perhaps you ran RStudio with `sudo RStudio` or something similar, and those files ended up owned by root?
