### ISSUE TITLE
RStudio Desktop on Linux won't start if ~/.config/RStudio/desktop.ini isn't readable

### ISSUE THREAD

**Issue by HeenaSaini** [rstudio/rstudio#12963]
Hi i have installed 
RSTUDIO-2023.03.0-386-AMD64.DEB. I am getting this error:

heena@heena-HP-Z240-Tower-Workstation:~$ rstudio
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/heena/.config/RStudio/desktop.ini'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at c.append (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183934)
    at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183448)
    at e.exports (/usr/lib/rstudio/resources/app/.webpack/main/index.js:8:183067)
    at new c (/usr/lib/rstudio/resources/app/.webpack/main/index.js:19:50744)
    at 7723 (/usr/lib/rstudio/resources/app/.webpack/main/index.js:19:52204)
    at __webpack_require__ (/usr/lib/rstudio/resources/app/.webpack/main/index.js:19:179183)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[37421:0406/144416.928942:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

When I run : sudo rstudio --no-sandboxup : it is still not working 

heena@heena-HP-Z240-Tower-Workstation:~sudo rstudio --no-sandboxup
[37152:0406/144221.047886:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144221.047934:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[37184:0406/144221.082235:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[37184:0406/144221.083549:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[37152:0406/144221.230566:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144221.241101:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[37227:0406/144221.253981:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[37227:0406/144221.255093:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[37236:0406/144221.261817:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=desktop-gl,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[37236:0406/144221.263375:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[37248:0406/144221.312707:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[37248:0406/144221.312840:ERROR:angle_platform_impl.cc(43)] Display.cpp:1014 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1014 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[37248:0406/144221.312938:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglInitialize: Not initialized.
[37248:0406/144221.313047:ERROR:gl_display.cc(917)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[37248:0406/144221.313172:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[37248:0406/144221.314494:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[37255:0406/144221.321148:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
[37255:0406/144221.323213:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 182452227
[37152:0406/144222.650590:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.804311:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.829953:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.850463:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.907437:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.926154:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144222.981126:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[37152:0406/144223.212570:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

Please help me

**Comment by gtritchie** [comment]
It appears you don't have access to a critical file:

> Error: EACCES: permission denied, open '/home/heena/.config/RStudio/desktop.ini'

What are the permissions of that file (desktop.ini)?

**Comment by gtritchie** [comment]
I could reproduce this problem by changing the permissions on `~/.config/RStudio/desktop.ini` to deny myself access. Then RStudio will fail to start with the error you saw.

I will fix RStudio so it starts even if this file isn't readable, but in the meantime, if you can change the permissions on this file so you have read access (or if you can delete it) then RStudio should start.

**Comment by HeenaSaini** [comment]
## R Session Startup Failure Report

### RStudio Version

RStudio 2023.03.0+386 "Cherry Blossom " (3c53477a, 2023-03-09) for Ubuntu
Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1.

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/home/heena/.local/share/rstudio/log/rsession-heena.log*

```
2023-04-11T16:56:35.731243Z [rsession-heena] WARNING The tcp http listener
initialized without signature validation: --verify-signatures option
missing; LOGGED FROM: void
rstudio::session::{anonymous}::initTcpHttpConnectionListener(const string&,
const string&, rstudio::session::Options&, const string&, const string&)
src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:76
2023-04-11T16:56:35.731510Z [rsession-heena] ERROR system error 2 (No such
file or directory) [path: ]; OCCURRED AT rstudio::core::Error
rstudio::r::session::discoverR(rstudio::r::session::RLocations*)
src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char*
const*) src/cpp/session/SessionMain.cpp:2452
2023-04-11T16:56:35.731510Z [rsession-heena] ERROR system error 2 (No such
file or directory) [path: ]; OCCURRED AT rstudio::core::Error
rstudio::r::session::discoverR(rstudio::r::session::RLocations*)
src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char*
const*) src/cpp/session/SessionMain.cpp:2452

```

**Comment by gtritchie** [comment]
You need to make desktop.ini readable.

**Comment by HeenaSaini** [comment]
I did: sudo chmod +rwx ~/.config/RStudio/desktop.ini

it is still not working

**Comment by gtritchie** [comment]
The fact you tried running RStudio via `sudo` at one point may have left a bunch of files with incorrect permissions. You shouldn't run RStudio via sudo.

As a test, try the following:

```bash
sudo mv ~/.config/RStudio ~/.config/RStudio.save
sudo mv ~/.config/rstudio ~/.config/rstudio.save
```

Then try running RStudio again (NOT with sudo).

**Comment by gtritchie** [comment]
Also what operating system are you using? That information was requested in the issue template but you deleted it.

**Comment by gtritchie** [comment]
I mentioned not running with sudo because you wrote: "When I run : sudo rstudio --no-sandboxup : it is still not working".

Let me know how it goes after you rename those folders.

**Comment by jonvanausdeln** [comment]
I tested on Desktop 2023.05.0-daily+210
Ubuntu 22.04

I was able to reproduce the issue with older build (by installing QT version, then changing permission of `desktop.ini`) and confirmed it was fixed for me after installing the daily.

I will wait for confirmation for OP to close.

**Comment by HeenaSaini** [comment]
As you can see the problem still persists on my side. Please see the
scrrenshot attached.

**Comment by HeenaSaini** [comment]
Even after renaming the folders, Rstudio is NOT starting

**Comment by HeenaSaini** [comment]
Hi

I created a fresh conda environment and then ran rstudio-latest version,
Now it is running but still has these errors/warning: but it is running
good .. thanks for your help!

libva error: vaGetDriverNameByIndex() failed with unknown libva error,
driver_name = (null)
[96016:0412/130236.876442:ERROR:gpu_init.cc(523)] Passthrough is not
supported, GL is desktop, ANGLE is
[96016:0412/130236.896739:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
[96016:0412/130236.896879:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
[96016:0412/130236.896968:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
[96016:0412/130236.897050:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
[96016:0412/130236.897131:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
[96016:0412/130236.897226:ERROR:gbm_wrapper.cc(255)] Failed to export
buffer to dma_buf: No such file or directory (2)
