### ISSUE TITLE
QUARTO_ENABLED=FALSE does not cleanly disable Quarto

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#13558]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.2+561
    OS Version      : FreeBSD 13.2

### Steps to reproduce the problem
Build with ```-DQUARTO_ENABLED=FALSE```.

### Describe the problem in detail
NodeJS fails with quarto-related errors:
```
--- src/gwt/CMakeFiles/gwt_build.dir/all ---
     [exec] [4/4] Building fresh packages...
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.error /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo: Command failed.
     [exec] 
     [exec] Exit code: 1
     [exec] Command: node install.js
     [exec] Arguments: 
     [exec] Directory: /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo
     [exec] Output:
     [exec] /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo/node-platform.js:38
     [exec]     throw new Error(`Unsupported platform: ${platformKey}`);
     [exec]           ^
     [exec] 
     [exec] Error: Unsupported platform: freebsd x64 LE
     [exec]     at pkgAndSubpathForCurrentPlatform (/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo/node-platform.js:38:11)
     [exec]     at checkAndPreparePackage (/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo/install.js:260:28)
     [exec]     at Object.<anonymous> (/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/turbo/install.js:310:1)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
     [exec]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
     [exec]     at Module.load (node:internal/modules/cjs/loader:1119:32)
     [exec]     at Module._load (node:internal/modules/cjs/loader:960:12)
     [exec]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     [exec]     at node:internal/main/run_main_module:23:47
     [exec] 
     [exec] Node.js v18.17.0
     [exec] info This module is OPTIONAL, you can safely ignore this error
     [exec] warning Error running install script for optional dependency: "/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba: Command failed.
     [exec] Exit code: 1
     [exec] Command: node-pre-gyp install --fallback-to-build
     [exec] Arguments: 
     [exec] Directory: /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba
     [exec] Output:
     [exec] node-pre-gyp info it worked if it ends with ok
     [exec] node-pre-gyp info using node-pre-gyp@1.0.10
     [exec] node-pre-gyp info using node@18.17.0 | freebsd | x64
     [exec] node-pre-gyp info check checked for \"/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release/nodejieba.node\" (not found)
     [exec] node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-freebsd-x64.tar.gz
     [exec] node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-freebsd-x64.tar.gz 
     [exec] node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@18.17.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
     [exec] node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-freebsd-x64.tar.gz 
     [exec] gyp info it worked if it ends with ok
     [exec] gyp info using node-gyp@9.4.0
     [exec] gyp info using node@18.17.0 | freebsd | x64
     [exec] gyp info ok 
     [exec] gyp info it worked if it ends with ok
     [exec] gyp info using node-gyp@9.4.0
     [exec] gyp info using node@18.17.0 | freebsd | x64
     [exec] gyp info find Python using Python version 3.9.17 found at \"/usr/local/bin/python3.9\"
     [exec] gyp info spawn /usr/local/bin/python3.9
     [exec] gyp info spawn args [
     [exec] gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
     [exec] gyp info spawn args   'binding.gyp',
     [exec] gyp info spawn args   '-f',
     [exec] gyp info spawn args   'make',
     [exec] gyp info spawn args   '-I',
     [exec] gyp info spawn args   '/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/config.gypi',
     [exec] gyp info spawn args   '-I',
     [exec] gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
     [exec] gyp info spawn args   '-I',
     [exec] gyp info spawn args   '/usr/ports/devel/RStudio/work-desktop/.cache/node-gyp/18.17.0/include/node/common.gypi',
     [exec] gyp info spawn args   '-Dlibrary=shared_library',
     [exec] gyp info spawn args   '-Dvisibility=default',
     [exec] gyp info spawn args   '-Dnode_root_dir=/usr/ports/devel/RStudio/work-desktop/.cache/node-gyp/18.17.0',
     [exec] gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
     [exec] gyp info spawn args   '-Dnode_lib_file=/usr/ports/devel/RStudio/work-desktop/.cache/node-gyp/18.17.0/<(target_arch)/node.lib',
     [exec] gyp info spawn args   '-Dmodule_root_dir=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba',
     [exec] gyp info spawn args   '-Dnode_engine=v8',
     [exec] gyp info spawn args   '--depth=.',
     [exec] gyp info spawn args   '--no-parallel',
     [exec] gyp info spawn args   '--generator-output',
     [exec] gyp info spawn args   'build',
     [exec] gyp info spawn args   '-Goutput_dir=.'
     [exec] gyp info spawn args ]
     [exec] gyp info ok 
     [exec] gyp info it worked if it ends with ok
     [exec] gyp info using node-gyp@9.4.0
     [exec] gyp info using node@18.17.0 | freebsd | x64
     [exec] gyp info spawn gmake
     [exec] gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
     [exec] gmake[5]: Entering directory '/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build'
     [exec]   CXX(target) Release/obj.target/nodejieba/lib/index.o
     [exec]   CXX(target) Release/obj.target/nodejieba/lib/nodejieba.o
     [exec] In file included from ../lib/nodejieba.cpp:5:
     [exec] In file included from ../deps/cppjieba/Jieba.hpp:4:
     [exec] In file included from ../deps/cppjieba/QuerySegment.hpp:8:
     [exec] In file included from ../deps/cppjieba/DictTrie.hpp:13:
     [exec] ../deps/limonp/StringUtil.hpp:87:70: error: no member named 'ptr_fun' in namespace 'std'
     [exec]   s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))));
     [exec]                                                                 ~~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:87:86: error: expected '(' for function-style cast or type construction
     [exec]   s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))));
     [exec]                                                                              ~~~~~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:87:92: error: expected '(' for function-style cast or type construction
     [exec]   s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))));
     [exec]                                                                                        ~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:92:61: error: no member named 'ptr_fun' in namespace 'std'
     [exec]   s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))).base(), s.end());
     [exec]                                                        ~~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:92:77: error: expected '(' for function-style cast or type construction
     [exec]   s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))).base(), s.end());
     [exec]                                                                     ~~~~~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:92:83: error: expected '(' for function-style cast or type construction
     [exec]   s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))).base(), s.end());
     [exec]                                                                               ~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:101:70: error: no member named 'bind2nd' in namespace 'std'
     [exec]   s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::bind2nd(std::equal_to<char>(), x))));
     [exec]                                                                 ~~~~~^
     [exec] ../deps/limonp/StringUtil.hpp:106:61: error: no member named 'bind2nd' in namespace 'std'
     [exec]   s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::bind2nd(std::equal_to<char>(), x))).base(), s.end());
     [exec]                                                        ~~~~~^
     [exec] In file included from ../lib/nodejieba.cpp:5:
     [exec] In file included from ../deps/cppjieba/Jieba.hpp:4:
     [exec] In file included from ../deps/cppjieba/QuerySegment.hpp:8:
     [exec] ../deps/cppjieba/DictTrie.hpp:143:12: warning: variable 'lineno' set but not used [-Wunused-but-set-variable]
     [exec]     size_t lineno = 0;
     [exec]            ^
     [exec] ../deps/cppjieba/DictTrie.hpp:208:17: warning: variable 'lineno' set but not used [-Wunused-but-set-variable]
     [exec]     for (size_t lineno = 0; getline(ifs, line); lineno++) {
     [exec]                 ^
     [exec] 2 warnings and 8 errors generated.
     [exec] gmake[5]: *** [nodejieba.target.mk:112: Release/obj.target/nodejieba/lib/nodejieba.o] Error 1
     [exec] gmake[5]: Leaving directory '/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build'
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: `gmake` failed with exit code: 2
     [exec] gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
     [exec] gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
     [exec] gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
     [exec] gyp ERR! System FreeBSD 13.2-STABLE
     [exec] gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release/nodejieba.node\" \"--module_name=nodejieba\" \"--module_path=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release\" \"--napi_version=9\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v108\"
     [exec] gyp ERR! cwd /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba
     [exec] gyp ERR! node -v v18.17.0
     [exec] gyp ERR! node-gyp -v v9.4.0
     [exec] gyp ERR! not ok 
     [exec] node-pre-gyp ERR! build error 
     [exec] node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
     [exec] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
     [exec] node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
     [exec] node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
     [exec] node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
     [exec] node-pre-gyp ERR! System FreeBSD 13.2-STABLE
     [exec] node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
     [exec] node-pre-gyp ERR! cwd /usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba
     [exec] node-pre-gyp ERR! node -v v18.17.0
     [exec] node-pre-gyp ERR! node-pre-gyp -v v1.0.10
     [exec] node-pre-gyp ERR! not ok 
     [exec] Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/lib/quarto/node_modules/nodejieba/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)"

BUILD FAILED
/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/build.xml:175: The following error occurred while executing this line:
/usr/ports/devel/RStudio/work-desktop/rstudio-2023.06.2-561/src/gwt/build.xml:132: exec returned: 1
```

```-DQUARTO_ENABLED=FALSE``` should disable Quarto in all parts of the project, including in the NodeJS code.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
@yurivict The `QUARTO_ENABLED` flag is not meant for panmirror (the visual editor). The flag does change whether [Quarto](https://github.com/quarto-dev/quarto-cli/) is allowed to be used. The panmirror code repository is `quarto-dev/quarto` and was moved there as an external dependency. It is now a shared component with RStudio's visual editor and Quarto's visual editor. Both projects depend on this component and panmirror happens to live in the Quarto org.

Your error message means that the [`quarto-dev/quarto`](https://github.com/quarto-dev/quarto/) project had a problem building panmirror. If the panmirror build doesn't work on your platform, you can file a bug at https://github.com/quarto-dev/quarto/. You want to be sure that this portion of `quarto-dev/quarto` can be built: https://github.com/quarto-dev/quarto/tree/main/apps/panmirror

Setting the flag to `false` doesn't change anything with your error because it is not meant to disable panmirror. There is no flag to do that, nor would you want to disable it.
