### ISSUE TITLE
Quarto Document saved on Google Drive (Windows) won't render

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#13813]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0-daily+193 (but also happens in earlier versions
    OS Version      : Windows 11
    R Version       : 4.3.0

### Steps to reproduce the problem
1. Map Google Drive (default from Google Drive app is G:\My Drive)
2. Create quarto document and save to Google Drive
3. Render document

### Describe the problem in detail

Render fails with

'''
ERROR: NotFound: The system cannot find the file specified. (os error 2): remove 'testfile_files\mediabag'

Stack trace:
    at Object.removeSync (ext:deno_fs/30_fs.js:197:7)
    at removeIfEmptyDir (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5344:18)
    at renderCleanup (file:///C:/PROGRA~1/Quarto/bin/quarto.js:68743:5)
    at file:///C:/PROGRA~1/Quarto/bin/quarto.js:69492:50
    at withTiming (file:///C:/PROGRA~1/Quarto/bin/quarto.js:19431:25)
    at Object.complete (file:///C:/PROGRA~1/Quarto/bin/quarto.js:69492:17)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Object.onPostProcess (file:///C:/PROGRA~1/Quarto/bin/quarto.js:75523:36)
    at async renderFileInternal (file:///C:/PROGRA~1/Quarto/bin/quarto.js:75507:5)
    at async renderFiles (file:///C:/PROGRA~1/Quarto/bin/quarto.js:75290:17)
'''

### Describe the behavior you expected
Expect that document renders correclty

NOTE: Other document types (RMarkdown, R Script) all seem to behave correctly.

 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
This also fails on Windows with Quarto CLI or VS code extension, with the same error. We should file this in quarto-dev/quarto-cli

**Comment by jgutman** [comment]
I believe it's already been filed, I think it's the same as this issue: https://github.com/quarto-dev/quarto-cli/issues/4614
