### ISSUE TITLE
Error When Rendering Quarto Document with Commented YAML Output Format

### ISSUE THREAD

**Issue by jan-abel-inwt** [rstudio/rstudio#13876]
I'm trying to render quarto documents with comments on the same line in the YAML header specifying the output format. This is a common practice for documentation purposes, and it should not result in rendering errors.

### System details

- **RStudio Edition**: Desktop
- **RStudio Version**: 2023.09.1
- **OS Version**: Pop!_OS - 22.04 LTS
- **R Version**: 4.3.1 (2023-06-16)

### Steps to reproduce the problem
1. Open RStudio.
2. Create or open a quarto document with a YAML header specifying the output format, e.g., `format: html`.
3. In the YAML header, add a comment on the same line after the format specification, e.g., `format: html #or pdf`.
4. Attempt to render the document using the RStudio rendering option or the shortcut `<CTRL + SHIFT + K>`.
5. Observe the error message and behavior.

The error message indicates:

```
ERROR: Unknown format pdf #or pdf

Error: Unknown format pdf #or pdf
    at resolveFormats (file:///opt/quarto/bin/quarto.js:83183:19)
    at async renderContexts (file:///opt/quarto/bin/quarto.js:82637:21)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:86520:28)
    at async render (file:///opt/quarto/bin/quarto.js:90681:21)
    at async renderForPreview (file:///opt/quarto/bin/quarto.js:102415:26)
    at async render (file:///opt/quarto/bin/quarto.js:102310:20)
    at async preview (file:///opt/quarto/bin/quarto.js:102316:21)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:103767:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127542:5)
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and the issue still persists.
- [ ] I have included a diagnostics report if this issue involves an RStudio crash.
- [x] I have provided a minimal, self-contained set of instructions for consistently reproducing the issue.

### Additional Information
- This issue does not occur when rendering the quarto document using the `quarto render` command from the terminal.
- The issue seems specific to the RStudio IDE.

**Comment by kevinushey** [comment]
Thanks for the bug report; we've confirmed this is an issue on the RStudio IDE side. I'll take a look.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+278](https://dailies.rstudio.com/version/2023.12.0-daily+278)
Windows 11

Comments in the YAML are now respected
