### ISSUE TITLE
RStudio JavaScript Schema Error on opening and when selecting Global Options

### ISSUE THREAD

**Issue by shreyavut** [rstudio/rstudio#14043]
### System details

    RStudio Edition :  Desktop 
    RStudio Version :  2023.09
    OS Version      :  Platform: x86_64-apple-darwin20 (64-bit), macOS Monterey 12.7
    R Version       :  4.3.2 (2023-10-31)

### Steps to reproduce the problem

I believe this started when I attempted to render a very large `mapview` object. RStudio crashed and then when I tried to re-open the application, this error popped up. 

`Uncaught Exception:
Error: Config schema violation: view/zoomLevel must be >= 0.25
at e.exports._validate (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:50391)
at set store [as store] (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:49350)
at e.exports.set (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:48118)
at D.zoomLevel (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:19:52659)
at IpcMainImpl.<anonymous> (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:19:20524)
at IpcMainImpl.emit (node:events:513:28)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:90214)
at WebContents.emit (node:events:513:28)`

Once I click `OK` about 3 times, RStudio proceeds to load. Then when I go to Tools -> Global Options, the error pops up again, and RStudio freezes. I've troubleshooted this with several different versions of RStudio and R, resetting the desktop state and removing all .Rdata, .Renviron, and .Rsession files. [This error](https://github.com/rstudio/rstudio/issues/11984) from about a year ago seemed to be the closest to what I'm experiencing, but even after cleaning up all the files, using App Cleaner and re-installing RStudio and R, the problem persists. I believe the error might be a corrupt .plist file, but I'm unsure how to approach this to make RStudio function normally without the error popping up. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@shreyavut Thank you for raising the issue! A couple of thingsL
- Can you provide the logs for RStudio Desktop? You can retrieve them using <kbd>Help -> Diagnostics -> Show Log Files</kbd>
- Can you provide the code that you think triggered the problem?

**Comment by ronblum** [comment]
@shreyavut Also, you might try resetting the RStudio state to see if you can get it out of whatever might be causing a problem: https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
