### ISSUE TITLE
Have `Run All Chunks Above` per language

### ISSUE THREAD

**Issue by SchmidtPaul** [rstudio/rstudio#14351]
I am writing a quarto document with Python and R code side by side:

``````
---
title: "R & Python chunks"
---

```{r}
library(dplyr)
r <- 1
```


```{python}
import math
p=1
```


```{r}
r+2
```


```{python}
p+2
```
``````

If I press `Run All Chunks Above` on a new Python chunk at the end, I will get:
```
>>> # Chunk 1 
>>> library(dplyr) Traceback (most recent call last):   File "<string>", line 1, in <module> NameError: name 'library' is not defined 
>>> r <- 1 Traceback (most recent call last):   File "<string>", line 1, in <module> TypeError: '<' not supported between instances of 'R' and 'int' 
>>>  
>>> # Chunk 2 
>>> import math 
>>> p=1 
>>>  
>>> # Chunk 3 
>>> r+2 Traceback (most recent call last):   File "<string>", line 1, in <module> TypeError: unsupported operand type(s) for +: 'R' and 'int' 
>>>  
>>> # Chunk 4 
>>> p+2 
3
```

If I press `Run All Chunks Above` on a new R chunk at the end, I will get:
```
> # Chunk 1
> library(dplyr)
> r <- 1
> 
> # Chunk 2
> import math
Fehler: unerwartetes Symbol in "import math"
```

So for Python it seems to at least work anyway, but for R it does not so that I need to manually run all R chunks above. Is there a more elegant way?

**Comment by ronblum** [comment]
@SchmidtPaul Thank you for raising this! We've marked this for review.

**Comment by ronblum** [comment]
Ref issue rstudio/rstudio-pro#5607.

**Comment by ronblum** [comment]
Ref issue #13572

**Comment by d-morrison** [comment]
Just ran into similar behavior with both `Run all` and `source("~/.active-rstudio-document")`. This limitation makes developing dual-language .Rmd and .qmd files much more difficult, since it appears we have to either render the whole document (and hope for no bugs) or run each chunk manually.
