### ISSUE TITLE
Intermittent Mac Desktop build failures due to different SHAs on non-binary files

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14773]
Mac builds are failing occasionally with this error:

```
[2024-05-31T07:18:02.129Z] # Building universal Desktop application.
[2024-05-31T07:18:02.129Z] - [i] x64AppPath: /Users/user193109/workspace/IDE/Pro-Builds/Platforms/macos-pipeline/main/src/node/desktop/../desktop-build-x86_64/out/RStudio-darwin-x64/RStudio.app
[2024-05-31T07:18:02.129Z] - [i] arm64AppPath: /Users/user193109/workspace/IDE/Pro-Builds/Platforms/macos-pipeline/main/src/node/desktop/../desktop-build-arm64/out/RStudio-darwin-arm64/RStudio.app
[2024-05-31T07:18:06.181Z] /Users/user193109/workspace/IDE/Pro-Builds/Platforms/macos-pipeline/main/package/osx/scripts/node_modules/@electron/universal/dist/cjs/index.js:89
[2024-05-31T07:18:06.181Z]                 throw new Error(`Expected all non-binary files to have identical SHAs when creating a universal build but "${file.relativePath}" did not`);
[2024-05-31T07:18:06.181Z]                       ^
[2024-05-31T07:18:06.181Z] 
[2024-05-31T07:18:06.181Z] Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Resources/app/.webpack/main/index.js" did not
[2024-05-31T07:18:06.181Z]     at exports.makeUniversalApp (/Users/user193109/workspace/IDE/Pro-Builds/Platforms/macos-pipeline/main/package/osx/scripts/node_modules/@electron/universal/dist/cjs/index.js:89:23)
[2024-05-31T07:18:06.181Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-31T07:18:06.181Z]     at async file:///Users/user193109/workspace/IDE/Pro-Builds/Platforms/macos-pipeline/main/package/osx/scripts/merge-electron.mjs:23:3
```

I haven't gone back to confirm, but it seems to have started recently, the most likely suspect is the package updates done here: https://github.com/rstudio/rstudio/pull/14593

**Comment by gtritchie** [comment]
Moving to next release, as we're still waiting on moving to a new build infrastructure.
