### ISSUE TITLE
RStudio Fails to Start on MacOs Intel Sonoma

### ISSUE THREAD

**Issue by Cade-Finch** [rstudio/rstudio#15095]
### System details

    RStudio Edition : MacOS 12+ Desktop
    RStudio Version :  2024.04.2
    OS Version      :  Sonoma 14.6
    R Version       :  4.4.1

### Steps to reproduce the problem

Download R 
Download RStudio
Open R
Open RStudio

### Describe the problem in detail

When I try to start RStudio for the first time, it says "Error Starting R"..."The R session failed to start. There are no error codes shown. I tried deleting and reinstalling both R and RStudio. R opens and runs. Below is the problem report: 

### RStudio Version

RStudio 2024.04.2+764 "Chocolate Cosmos " (e4392fc9, 2024-06-05) for macOS

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*MISSING VALUE*

```
MISSING VALUE
```

Problem persists when run in terminal or running the executable. Running the executable gives:

user@MacBook-Pro-4 ~ % /Applications/RStudio.app/Contents/MacOS/RStudio ; exit;
Error: EACCES: permission denied, mkdir '/Users/user/.local/share/rstudio/log'
    at Object.mkdirSync (node:fs:1398:3)
    at e.exports._createLogDirIfNotExist (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:310634)
    at new e.exports (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:304923)
    at new t.WinstonLogger (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:337489)
    at t.ArgsManager.handleLogLevel (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:355058)
    at Object.startup (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:20:41494)
    at async Object.main (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:20:40331) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/Users/user/.local/share/rstudio/log'
}
2024-08-27 18:19:55.075 RStudio[22421:1521500] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

### Describe the behavior you expected

I expected RStudio to open. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Cade-Finch Thank you for raising this! I've marked this for review.

Note: See this issue at Jython which links to OpenJDK bugs: https://github.com/jython/jython/issues/324#issuecomment-2041021699
