### ISSUE TITLE
Update to Electron 32.x

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15129]
The Kousa-Dogwood desktop uses Electron 31.x, and Electron 32.x is now the newest supported version.

For reference, Cranberry Hibiscus is using Electron 30.x.

Electron | Alpha | Beta | Stable | EOL | Chrome | Node | Supported
-- | -- | -- | -- | -- | -- | -- | --
33.0.0 | 2024-Aug-22 | 2024-Sep-18 | 2024-Oct-15 | 2025-Apr-29 | M130 | TBD | ✅
32.0.0 | 2024-Jun-14 | 2024-Jul-24 | 2024-Aug-20 | 2025-Mar-04 | M128 | v20.16 | ✅
31.0.0 | 2024-Apr-18 | 2024-May-15 | 2024-Jun-11 | 2025-Jan-07 | M126 | v20.14 | ✅
30.0.0 | 2024-Feb-22 | 2024-Mar-20 | 2024-Apr-16 | 2024-Oct-15 | M124 | v20.11 | ✅

## Note

Most Electron updates are relatively trivial (update the package.json and lockfile), but this one causes a build failure (on Mac, at least), when building the native node modules, so could be more involved:

```
> rstudio@9999.99.9-dev+1.test9 postinstall
> npx electron-rebuild && ts-node scripts/generate.ts

⠋ Building module: msgpackr-extract, Completed: 0  CXX(target) Release/obj.target/extract/src/extract.o
In file included from ../src/extract.cpp:10:
In file included from /Users/gary/.electron-gyp/32.0.2/include/node/v8.h:23:
In file included from /Users/gary/.electron-gyp/32.0.2/include/node/cppgc/common.h:8:
/Users/gary/.electron-gyp/32.0.2/include/node/v8config.h:13:2: error: "C++20 or later required."
#error "C++20 or later required."
 ^
1 error generated.
make: *** [Release/obj.target/extract/src/extract.o] Error 1
Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/Users/gary/alt/rstudio/src/node/desktop/node_modules/node-gyp/lib/build.js:203:23)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/gary/alt/rstudio/src/node/desktop/node_modules/msgpackr-extract'

Error: node-gyp failed to rebuild '/Users/gary/alt/rstudio/src/node/desktop/node_modules/msgpackr-extract'
    at ChildProcess.<anonymous> (/Users/gary/alt/rstudio/src/node/desktop/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by gtritchie** [comment]
https://github.com/electron/electron/issues/43510

**Comment by icebob** [comment]
Same issue. The native module rebuild works with Electron 31, but C++20 error with Electron 32

**Comment by gtritchie** [comment]
We're sticking with Electron 31 for Kousa Dogwood; moving this issue to next release.

**Comment by gtritchie** [comment]
Moved back to in-progress. Builds are failing on both focal and opensuse15 with issues building the native node modules.

**Comment by gtritchie** [comment]
I'm downgrading the 2024.12.1 branch back to Electron 31.x while I work on the build issues with Electron 32+ on Focal and Opensuse/leap 15.5.

**Comment by gtritchie** [comment]
## Notes on Build Problems

With the update to Electron 33, RStudio Desktop currently won't build on OpenSUSE15 or Ubuntu Focal. The native-node modules fail with the error:

g++: error: unrecognized command line option '-std=gnu++20'; did you mean '-std=gnu++03'?

This is due to these platforms not having gcc10 or above. This requirement is mentioned in the Electron 33 release notes here: https://www.electronjs.org/blog/electron-33-0#behavior-changed-native-modules-now-require-c20

I was able to install and select gcc10 on Ubuntu Focal and then build RStudio, but am still working on fixing OpenSuse15.6.

I still need to check if Server and Workbench will build and function with the newer gcc, as well.

I also tested with Electron 32.x, and hit the same problem.

**Comment by gtritchie** [comment]
Closing this; we'll stick with Electron 31 for the Kousa Dogwood patch. There are at least two known issues with moving to Electron 32 or 33:

- native node modules won't compile on opensuse15 or focal due to old gcc
- license dialog doesn't work correctly on Desktop Pro (you can browse to a license file and select it, but it doesn't get populated into the dialog)

Given that and the short timeline for the patch, closing this and we'll tackle the Electron upgrade in Mariposa Orchid via #15450.
