### ISSUE TITLE
Quarto: can not render a PDF (quarto or the render pipeline looks for a non-existent log file)

### ISSUE THREAD

**Issue by WildPenquin** [rstudio/rstudio#15198]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2 Build 764
    OS Version      : Arch Linux
    R Version       : 4.4.1

#### Version information from R-Studio dialog:
```
RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.555
```

#### Version information from R-> version

```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          4.1                         
year           2024                        
month          06                          
day            14                          
svn rev        86737                       
language       R                           
version.string R version 4.4.1 (2024-06-14)
nickname       Race for Your Life    

```
### Steps to reproduce the problem

1. Create a simple test Quarto document (the default template is fine).
2. Set PDF as output (when creating or manually after creating in any document)
3. Click "render"

### Describe the problem in detail

The render will fail with:
`ERROR: NotFound: No such file or directory (os error 2): readfile 'Test.log'`

There is no Test.log in the working directory, nor in the directory containing the .qmd, even if these are the same directory (I've changed the working directory to source file location). There is no *.log files anywhere I could think of where RStudio could put them (I've searched with find),

Curiously, the intermediary files such as the graph files (if any) and .tex file are created, and I can render the file manually by opening the tex file in any tex editor (or even from command line).

### Describe the behavior you expected

A nice PDF file should be produced when clicking "=> Render".

#### The example document RStudio creates when making a new Quatro document attached, but renamed to .txt (github does not allow attaching .qmd)
[Test.txt](https://github.com/user-attachments/files/17051793/Test.txt)

#### The full output from => Render:
```
==> quarto preview Test.qmd --to pdf --no-watch-inputs --no-browse



processing file: Test.qmd
                                                                                                            
output file: Test.knit.md

pandoc 
  to: latex
  output-file: Test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Test
  author: WildPenguin
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  ---! /var/lib/texmf/web2c/xetex/xelatex.fmt made by different executable version, strings are different
  (Fatal format file error; I'm stymied)
  
updating tlmgr

updating existing packages
ERROR: NotFound: No such file or directory (os error 2): readfile 'Test.log'
Path: Test.log

Stack trace:
Path: Test.log
    at readTextFileSync (ext:deno_fs/30_fs.js:733:14)
    at Object.Deno.readTextFileSync (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5625:25)
    at initialCompileLatex (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:76185:18)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async generatePdf (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:76131:22)
    at async Object.complete (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:76411:27)
    at async file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:70095:31
    at async withTimingAsync (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:19466:25)
    at async Object.complete (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:70093:13)
    at async Object.onPostProcess (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:77272:36)
```

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This part of the output:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  ---! /var/lib/texmf/web2c/xetex/xelatex.fmt made by different executable version, strings are different
  (Fatal format file error; I'm stymied)
```

makes me think there's some issue with the TeX installation itself; it seems like the issue lies outside of RStudio / Quarto.

**Comment by gtritchie** [comment]
Closing due to lack of activity.
