### ISSUE TITLE
RStudio takes different quarto/python installation than quarto in command line

### ISSUE THREAD

**Issue by sebacea** [rstudio/rstudio#15350]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.9.0.375
    OS Version      : macOS Sequoia 15.0.1
    R Version       : 4.4.1

### Steps to reproduce the problem

New quarto document> Create (engine: Jupyter and kernel: Python3) > Render > Save (template) as `Sin título.qmd`

### Describe the problem in detail

```
==> quarto preview Sin título.qmd --to html --no-watch-inputs --no-browse


Starting python3 kernel...Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
Python 3 installation:
  Version: 3.9.6
  Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
  Jupyter: (None)

Jupyter is not available in this Python installation.
Install with python3 -m pip install jupyter
```

### Describe the behavior you expected

To render the template as normal. If I execute `quarto preview Sin\ título.qmd` in the terminal tab the result is as expected:

```
Starting python3 kernel...Done

Executing 'Sin título.quarto_ipynb'
  Cell 1/1: 'fig-polar'...Done

pandoc 
  to: html
  output-file: Sin título.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: matplotlib demo
  jupyter: python3
  
Output created: Sin título.html

Watching files for changes
Browse at http://localhost:7135/
```

Because quarto from terminal is fine:

```
quarto check jupyter
Quarto 1.5.57
[✓] Checking Python 3 installation....OK
      Version: 3.11.0 (Conda)
      Path: /Users/sebacea/anaconda3/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.11, julia-1.10, ir, julia-1.9, julia-1.7, julia-0.6, python3

[✓] Checking Jupyter engine render....OK
```

- [*] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [*] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [*] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [*] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sebacea Thank you for raising this! To clarify, the example has a space in the document name. Does this mean that the issue occurs only when there's a space in the name, but works fine if there isn't one?

**Comment by sebacea** [comment]
Hi @ronblum, I confirm that the issue occurs even if there is no space in the document's name:

```
==> quarto preview Sintítulo.qmd --to html --no-watch-inputs --no-browse


Starting python3 kernel...Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
Python 3 installation:
  Version: 3.9.6
  Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
  Jupyter: (None)

Jupyter is not available in this Python installation.
Install with python3 -m pip install jupyter
```

**Comment by gtritchie** [comment]
I was able to reproduce this with `2024.11.0-hourly+321`, `2024.09.1+394`, and `2024.04.2+764` so this isn't a regression (or at least not a recent one).

**Comment by sebacea** [comment]
My YAML is exactly the one of a “quarto document” template

**Comment by sebacea** [comment]
```
---
title: "matplotlib demo"
format:
  html:
    code-fold: true
jupyter: python3
---
```
