### ISSUE TITLE
Segmentation fault in `libQt5WebKit.so.5`

### ISSUE THREAD

**Issue by paulmenzel** [rstudio/rstudio#2598]
### System details

    RStudio Edition Desktop
    RStudio Version : 1.1.383 and 1.1.444
    OS Version      : Linux 4.14.30
    R Version       :  R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"

### Steps to reproduce the problem

Update from Qt 5.4.1 to 5.10.1.

### Describe the problem in detail

Typing `rstudio`, the windows is shortly visible (less than a second), and then it terminates with a segmentation fault.

Unfortunately, the Qt debug symbols are not installed.

```
[…]
Core was generated by `rstudio'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffae726b03c in ?? () from /usr/local/qt5/lib/libQt5WebKit.so.5
[…]
(gdb) t a a bt

Thread 15 (Thread 0x7ffacab66700 (LWP 31020)):
#0  0x00007ffae2608ff1 in __GI___poll (fds=0xb4ba70, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffae0313644 in g_main_context_iterate (priority=2147483647, n_fds=2, fds=0xb4ba70, timeout=<optimized out>, context=0xb0b500) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:4187
#2  0x00007ffae0313644 in g_main_context_iterate (context=0xb0b500, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3881
#3  0x00007ffae03139d2 in g_main_loop_run (loop=0xb09af0) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:4082
#4  0x00007ffae17616e6 in gdbus_shared_thread_func (user_data=0xb0b4d0) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/gio/gdbusprivate.c:275
#5  0x00007ffae033ab75 in g_thread_proxy (data=0xb8cb70) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gthread.c:784
#6  0x00007ffae3a36557 in start_thread (arg=0x7ffacab66700) at pthread_create.c:463
#7  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7ffa7affb700 (LWP 31095)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffa7affb700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7ffa79ff9700 (LWP 31097)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffa79ff9700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7ffa7b7fc700 (LWP 31094)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffa7b7fc700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7ffac0d4d700 (LWP 31092)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffac0d4d700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7ffa7bffd700 (LWP 31093)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffa7bffd700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7ffac39f1700 (LWP 31088)):
#0  0x00007ffae2608ff1 in __GI___poll (fds=0x7ffa74018e80, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffae0313644 in g_main_context_iterate (priority=2147483647, n_fds=4, fds=0x7ffa74018e80, timeout=<optimized out>, context=0x7ffa74000bf0) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:4187
#2  0x00007ffae0313644 in g_main_context_iterate (context=context@entry=0x7ffa74000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3881
#3  0x00007ffae031375c in g_main_context_iteration (context=0x7ffa74000bf0, may_block=1) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3947
#4  0x00007ffae3f206cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/qt5/lib/libQt5Core.so.5
#5  0x00007ffae3ecb78a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/qt5/lib/libQt5Core.so.5
#6  0x00007ffae3cf342c in QThread::exec() () at /usr/local/qt5/lib/libQt5Core.so.5
#7  0x00007ffae7db6555 in  () at /usr/local/qt5/lib/libQt5DBus.so.5
#8  0x00007ffae3cf836c in  () at /usr/local/qt5/lib/libQt5Core.so.5
#9  0x00007ffae3a36557 in start_thread (arg=0x7ffac39f1700) at pthread_create.c:463
#10 0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7ffac154e700 (LWP 31091)):
#0  0x00007ffae3a3c8b6 in __pthread_cond_timedwait (private=<optimized out>, abstime=0x7ffac154dd50, expected=0, futex_word=0x7ffaea85f258) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007ffae3a3c8b6 in __pthread_cond_timedwait (abstime=0x7ffac154dd50, mutex=0x7ffaea85f208, cond=0x7ffaea85f230) at pthread_cond_wait.c:539
#2  0x00007ffae3a3c8b6 in __pthread_cond_timedwait (cond=0x7ffaea85f230, mutex=0x7ffaea85f208, abstime=0x7ffac154dd50) at pthread_cond_wait.c:667
#3  0x00007ffae72dfbfa in WTF::ThreadCondition::timedWait(WTF::Mutex&, double) () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae6f9577c in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#6  0x00007ffae3a36557 in start_thread (arg=0x7ffac154e700) at pthread_create.c:463
#7  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7ffac23d4700 (LWP 31090)):
#0  0x00007ffae2608ff1 in __GI___poll (fds=0x7ffa70002ce0, nfds=1, timeout=10168) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffae0313644 in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x7ffa70002ce0, timeout=<optimized out>, context=0x7ffa70000bf0) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:4187
#2  0x00007ffae0313644 in g_main_context_iterate (context=context@entry=0x7ffa70000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3881
#3  0x00007ffae031375c in g_main_context_iteration (context=0x7ffa70000bf0, may_block=1) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3947
#4  0x00007ffae3f206cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/qt5/lib/libQt5Core.so.5
#5  0x00007ffae3ecb78a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/qt5/lib/libQt5Core.so.5
#6  0x00007ffae3cf342c in QThread::exec() () at /usr/local/qt5/lib/libQt5Core.so.5
#7  0x00007ffae3cf836c in  () at /usr/local/qt5/lib/libQt5Core.so.5
#8  0x00007ffae3a36557 in start_thread (arg=0x7ffac23d4700) at pthread_create.c:463
#9  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ffac9f03700 (LWP 31084)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffae7d89c24) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffae7d89bd0, cond=0x7ffae7d89bf8) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffae7d89bf8, mutex=0x7ffae7d89bd0) at pthread_cond_wait.c:655
#3  0x00007ffae72aa164 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72aa189 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffac9f03700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffac2bd5700 (LWP 31089)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea7dd4d0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea7dd480, cond=0x7ffaea7dd4a8) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea7dd4a8, mutex=0x7ffaea7dd480) at pthread_cond_wait.c:655
#3  0x00007ffae617139b in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae61715e9 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#6  0x00007ffae3a36557 in start_thread (arg=0x7ffac2bd5700) at pthread_create.c:463
#7  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffa7a7fa700 (LWP 31096)):
#0  0x00007ffae3a3c542 in __pthread_cond_wait (private=<optimized out>, expected=0, futex_word=0x7ffaea867d38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ffae3a3c542 in __pthread_cond_wait (abstime=0x0, mutex=0x7ffaea867ce8, cond=0x7ffaea867d10) at pthread_cond_wait.c:502
#2  0x00007ffae3a3c542 in __pthread_cond_wait (cond=0x7ffaea867d10, mutex=0x7ffaea867ce8) at pthread_cond_wait.c:655
#3  0x00007ffae6f96913 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#4  0x00007ffae72df6e1 in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffa7a7fa700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffacb367700 (LWP 31019)):
#0  0x00007ffae2608ff1 in __GI___poll (fds=0xa82e80, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffae0313644 in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0xa82e80, timeout=<optimized out>, context=0xa87d70) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:4187
#2  0x00007ffae0313644 in g_main_context_iterate (context=context@entry=0xa87d70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3881
#3  0x00007ffae031375c in g_main_context_iteration (context=0xa87d70, may_block=may_block@entry=1) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:3947
#4  0x00007ffae0313799 in glib_worker_main (data=<optimized out>) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gmain.c:5742
#5  0x00007ffae033ab75 in g_thread_proxy (data=0xb8cb20) at /dev/shm/bee-root/glib2/glib2-2.54.2-0/source/glib/gthread.c:784
#6  0x00007ffae3a36557 in start_thread (arg=0x7ffacb367700) at pthread_create.c:463
#7  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffad47e7700 (LWP 31018)):
#0  0x00007ffae2608ff1 in __GI___poll (fds=fds@entry=0x7ffad47e6c50, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffadc84aee2 in _xcb_conn_wait (c=c@entry=0xb128b0, cond=cond@entry=0xb128f0, vector=vector@entry=0x0, count=count@entry=0x0) at /dev/shm/bee-pmenzel/libxcb/libxcb-1.12-0/source/src/xcb_conn.c:479
#2  0x00007ffadc84cbf7 in xcb_wait_for_event (c=0xb128b0) at /dev/shm/bee-pmenzel/libxcb/libxcb-1.12-0/source/src/xcb_in.c:693
#3  0x00007ffad736a2c9 in  () at /usr/local/qt5/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#4  0x00007ffae3cf836c in  () at /usr/local/qt5/lib/libQt5Core.so.5
#5  0x00007ffae3a36557 in start_thread (arg=0x7ffad47e7700) at pthread_create.c:463
#6  0x00007ffae2612d1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffaea8d2240 (LWP 31004)):
#0  0x00007ffae726b03c in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#1  0x00007ffae726c76d in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#2  0x00007ffae726f6db in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#3  0x00007ffa7bfff0e5 in  ()
Python Exception <type 'exceptions.OverflowError'> long too big to convert: 
#4  0xffffffffffffffff in  ()#5  0x00007ffae70fe24a in  () at /usr/local/qt5/lib/libQt5WebKit.so.5
#6  0x00007ffa7bfff260 in  ()
#7  0x000000000000000a in  ()
#8  0x00007ffa47eccf80 in  ()
#9  0x000000000000000a in  ()
#10 0x00007ffa00000000 in  ()
#11 0x00007ffa4f50f830 in  ()
#12 0x00000000ffffffff in  ()
#13 0x00007ffa4cce5600 in  ()
#14 0x00007ffac00f4070 in  ()
#15 0x00007ffa7bfff260 in  ()
#16 0x00007ffaea7d0290 in  ()
#17 0x00007ffac014e180 in  ()
#18 0x0000000000000000 in  ()
```

**Comment by kevinushey** [comment]
Yes, RStudio only works with the version of Qt that it was compiled against.

RStudio v1.2 will be built against Qt 5.10.1 and we're also switching from WebKit to WebEngine. Daily builds of this branch are available at https://dailies.rstudio.com.

**Comment by kevinushey** [comment]
Sorry, I misunderstood that -- most often we see issues of this form when one builds RStudio against Qt 5.4.1 but attempts to run against a newer Qt.

Nonetheless, we're working actively to stabilize the daily builds of RStudio and hope to have at least a preview release of RStudio v1.2 prepared this summer.

**Comment by paulmenzel** [comment]
Updating to [Qt WebKit 5.212 from January 2018](http://download.qt.io/snapshots/ci/qtwebkit/5.212/1516463897/) fixed the crash.
