### ISSUE TITLE
I can load package sparkR but as.DataFrame fails

### ISSUE THREAD

**Issue by Silop7** [rstudio/rstudio#2904]
### System details
    RStudio Edition : Desktop
    RStudio Version : Version 1.1.447
    OS Version      : Windows 10 Professional
    R Version       : 3.4.4

### I am just starting with SparkR and I try to run the following code based on an online tutorial.
if (nchar(Sys.getenv("SPARK_HOME")) < 1) {
  Sys.setenv(SPARK_HOME = "C:\\Apache\\Spark\\Cache\\spark-2.3.0-bin-hadoop2.7")
}
library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R","lib")))
sparkR.session(master = "local[*]", appName = "SparkR",
               sparkHome = Sys.getenv("SPARK_HOME"), sparkConfig = list(spark.driver.memory = "1g"))

##I was able to initiate sparkR.session 
df <- as.DataFrame(iris)    ##But as.DataFrame still fails... 

### Describe the problem in detail
I am able to use sparklyr without any obvious issue but I cannot run as.DataFrame with sparkR.
Here is the error I am getting:
"
Error in handleErrors(returnStatus, conn) : 
  org.apache.spark.sql.AnalysisException: java.lang.RuntimeException: java.lang.RuntimeException: Error while running command to get file permissions : java.io.IOException: (null) entry in command string: null ls -F C:\tmp\hive
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:770)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
	at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1097)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.loadPermissionInfo(RawLocalFileSystem.java:659)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.getPermission(RawLocalFileSystem.java:634)
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:599)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionStat....."

**Comment by jmcphers** [comment]
This forum is for bug reports in the RStudio IDE itself. For help with sparklyr you might try the community forum:

https://community.rstudio.com/

or StackOverflow:

https://stackoverflow.com/
