### ISSUE TITLE
reticulate + matplotlib doesn't work on RStudio Cloud

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3675]
Attempting to import `matplotlib` gives the error:

```R
> reticulate::repl_python()
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'module' object has no attribute 'pyplot'
```

What's _really_ happening is that the import is failing:

```bash
rstudio-user@7bea121377aa:/cloud/project$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rstudio-user/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/rstudio-user/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/rstudio-user/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/rstudio-user/.local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
```

This occurs because the default backend is `TkAgg`, and requires TclTk libraries that are not installed. Enforcing an `Agg` backend fixes the problem:

```python
>>> matplotlib.get_backend()
'TkAgg'
>>> matplotlib.use('Agg')
>>> import matplotlib.pyplot
```

There's a couple potential fixes here:

1. `reticulate` could enforce the `Agg` backend when using `matplotlib`;
2. RStudio Cloud could set a default backend using a `matplotlibrc` file,
3. `reticulate` could provide some other mechanism for setting a default backend.

Note that `reticulate` currently has some code specifically for RStudio Desktop here:

https://github.com/rstudio/reticulate/blob/5541e21544ff64b21ad722a502b15c2b687f5ee1/R/knitr-engine.R#L215-L231

but perhaps that could be expanded to all versions of RStudio.

**Comment by kevinushey** [comment]
Should be fixed with https://github.com/rstudio/rstudio/commit/b255f02120fe61e2b9360112a7d06afc03561402.

**Comment by dfalty** [comment]
Verified on rstudio.cloud with version 1.2.1206-2.
