### ISSUE TITLE
RChunkHeaderParser tests broken on v1.3 (requireJS)

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4249]
The RChunkHeaderParser tests don't currently pass in RStudio 1.3. It looks like this may be a result of a change in Ace and/or RequireJS.

```
Buildfile: /Users/jmcphers/git/rstudio/src/gwt/build.xml

build-unittests:
    [javac] Compiling 13 source files to /Users/jmcphers/git/rstudio/src/gwt/bin

unittest:
     [java] JUnit version 4.9b3
     [java] ....................................................................................................................................................E...
     [java] Time: 67.072
     [java] There was 1 failure:
     [java] 1) testRMarkdownChunkHeader(org.rstudio.studio.client.workbench.views.source.editors.text.assist.RChunkHeaderParserTests)
     [java] com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot find function require in object [object Window].
     [java]     at org.rstudio.core.client.RegexUtil.$clinit(RegexUtil.java:43)
     [java]     at org.rstudio.studio.client.workbench.views.source.editors.text.assist.RChunkHeaderParser.parse(RegexUtil.java:49)
     [java]     at org.rstudio.studio.client.workbench.views.source.editors.text.assist.RChunkHeaderParserTests.testRMarkdownChunkHeader(RChunkHeaderParserTests.java:32)
     [java]     at Unknown.anonymous(GWTTestMetadataImpl.java:187)
     [java]     at com.google.gwt.junit.client.impl.GWTTestAccessor.$invoke(GWTTestAccessor.java:35)
     [java]     at com.google.gwt.junit.client.impl.GWTRunner.$executeTestMethod(GWTRunner.java:226)
     [java]     at com.google.gwt.junit.client.GWTTestCase.$doRunTest(GWTTestCase.java:157)
     [java]     at com.google.gwt.junit.client.GWTTestCase.$runBare(TestCase.java:59)
     [java]     at com.google.gwt.junit.client.GWTTestCase.$__doRunTest(GWTTestCase.java:115)
     [java]     at com.google.gwt.junit.client.impl.GWTRunner.$runTest(GWTRunner.java:302)
     [java]     at com.google.gwt.junit.client.impl.GWTRunner.$doRunTest(GWTRunner.java:235)
     [java]     at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.$onSuccess(GWTRunner.java:106)
     [java]     at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:100)
     [java]     at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
     [java]     at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
     [java]     at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
     [java]     at Unknown.anonymous(XMLHttpRequest.java:329)
     [java]     at com.google.gwt.core.client.impl.Impl.apply(Impl.java:239)
     [java]     at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:298)
     [java]     at Unknown.anonymous(Impl.java:77)
     [java]
     [java] FAILURES!!!
     [java] Tests run: 151,  Failures: 1
     [java]

BUILD FAILED
/Users/jmcphers/git/rstudio/src/gwt/build.xml:235: Java returned: 1
```

**Comment by jmcphers** [comment]
GWT tests pass now.

**Comment by gtritchie** [comment]
Reopening, the tests have been commented out since 2019 but I want to get them running again.

**Comment by gtritchie** [comment]
Nothing to verify, closing.
