### ISSUE TITLE
[ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#6088]
Build of 1.2.5033 fails with Java 11 and Java 13 on FreeBSD:
```
     [java] Compiling module org.rstudio.studio.RStudio
     [java]    [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
```
See the log: https://people.freebsd.org/~yuri/RStudio-1.2.5033.log

----------

Build with Java 8 is also broken, see http://beefy6.nyi.freebsd.org/data/120amd64-default/523698/logs/errors/RStudio-1.2.5033.log

```
     [java] [ERROR] Unexpected internal compiler error
     [java] java.lang.UnsatisfiedLinkError: sun.nio.fs.LinuxWatchService.inotifyInit()I
     [java] 	at sun.nio.fs.LinuxWatchService.inotifyInit(Native Method)
     [java] 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:59)
     [java] 	at sun.nio.fs.BsdFileSystem.newWatchService(BsdFileSystem.java:51)
     [java] 	at com.google.gwt.dev.resource.impl.ResourceAccumulator.maybeInitializeWatchService(ResourceAccumulator.java:98)
     [java] 	at com.google.gwt.dev.resource.impl.ResourceAccumulator.fullRefresh(ResourceAccumulator.java:89)
     [java] 	at com.google.gwt.dev.resource.impl.ResourceAccumulator.refreshResources(ResourceAccumulator.java:69)
     [java] 	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager.getResources(ResourceAccumulatorManager.java:113)
     [java] 	at com.google.gwt.dev.resource.impl.DirectoryClassPathEntry.findApplicableResources(DirectoryClassPathEntry.java:49)
     [java] 	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.scanResources(ResourceOracleImpl.java:263)
     [java] 	at com.google.gwt.dev.cfg.ModuleDef.ensureResourcesScanned(ModuleDef.java:731)
     [java] 	at com.google.gwt.dev.cfg.ModuleDef.getSourceResourceOracle(ModuleDef.java:567)
     [java] 	at com.google.gwt.dev.CompilerContext$Builder.initializeResourceOracles(CompilerContext.java:100)
     [java] 	at com.google.gwt.dev.CompilerContext$Builder.build(CompilerContext.java:48)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:193)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
     [java] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
```

**Comment by jmcphers** [comment]
This is an upstream issue; GWT does not compile with Java 11.

https://github.com/gwtproject/gwt/issues/9626
