### ISSUE TITLE
Windows builds soft-failing

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6730]
The Windows builds have been soft-failing for some time now. The builds are actually succeeding, but show up as failures in Jenkins because Jenkins is unable to delete the build folder.

```
[2020-04-24T18:49:35.042Z] Error when executing always post condition:
[2020-04-24T18:49:35.042Z] jenkins.util.io.CompositeIOException: Unable to delete 'c:\jenkins\workspace\IDE\windows-v1.3'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[2020-04-24T18:49:35.042Z] 	at jenkins.util.io.PathRemover.forceRemoveRecursive(PathRemover.java:99)
[2020-04-24T18:49:35.042Z] 	at hudson.Util.deleteRecursive(Util.java:294)
[2020-04-24T18:49:35.042Z] 	at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1271)
[2020-04-24T18:49:35.042Z] 	at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1267)
[2020-04-24T18:49:35.042Z] 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
[2020-04-24T18:49:35.042Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
[2020-04-24T18:49:35.042Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[2020-04-24T18:49:35.042Z] 	at hudson.remoting.Request$2.run(Request.java:369)
[2020-04-24T18:49:35.042Z] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
[2020-04-24T18:49:35.042Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2020-04-24T18:49:35.042Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2020-04-24T18:49:35.042Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2020-04-24T18:49:35.042Z] 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
[2020-04-24T18:49:35.042Z] 	at java.lang.Thread.run(Thread.java:748)
[2020-04-24T18:49:35.042Z] 	Suppressed: jenkins.util.io.CompositeIOException: Unable to remove directory c:\jenkins\workspace\IDE\windows-v1.3\package\win32\build\src\cpp with directory contents: []
```

Full logs: https://buildmaster.rstudioservices.com/job/IDE/job/windows-v1.3/920/consoleText

We should address this so that Windows builds begin reporting as successful. It might be as simple as adding a delay after upload to give the processes using the files time to exit (Jenkins only waits a fraction of a second).

**Comment by jmcphers** [comment]
Speculative fix: https://github.com/rstudio/rstudio/commit/8bc84fe8436812cc79e684b2ecd9ac1407a8a5d3

**Comment by jmcphers** [comment]
Well, that didn't help. Even after waiting 30 seconds, we see the same failure.

```
2020-04-27 14:02:37  Sleeping for 30 sec
2020-04-27 14:03:07  [Pipeline] }
2020-04-27 14:03:07  [Pipeline] // stage
2020-04-27 14:03:07  [Pipeline] stage
2020-04-27 14:03:07  [Pipeline] { (Declarative: Post Actions)
2020-04-27 14:03:07  [Pipeline] deleteDir
2020-04-27 14:03:42  Error when executing always post condition:
2020-04-27 14:03:42  jenkins.util.io.CompositeIOException: Unable to delete 'c:\jenkins\workspace\IDE\windows-v1.4'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
2020-04-27 14:03:42  	at jenkins.util.io.PathRemover.forceRemoveRecursive(PathRemover.java:99)
```

This error might be related:

```
2020-04-27 14:03:42  		Suppressed: java.nio.file.FileSystemException: c:\jenkins\workspace\IDE\windows-v1.4\package\win32\build\src\cpp: The process cannot access the file because it is being used by another process.
```

**Comment by jmcphers** [comment]
Next try:

https://github.com/rstudio/rstudio/commit/b042f6d4c53d8de7e1baa91e92566014e7907ecd

Inspection reveals that the `c:\jenkins\workspace\IDE\windows-v1.4\package\win32\build\src\cpp` folder is empty, so while it's not clear why we can't delete it, we can at least make it a warning instead of causing it to fail the build.

**Comment by jmcphers** [comment]
Third try's the charm! https://github.com/rstudio/rstudio/commit/61da8a91a57bc59bfb942bc6b1f635efaa3b54e3 worked.
