### ISSUE TITLE
rmarkdown console stalls with viridis color scales

### ISSUE THREAD

**Issue by nschan** [rstudio/rstudio#7044]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 20.04 LTS
    R Version       : 3.6.3

### Steps to reproduce the problem

````
---
title: "Test_viridis"
output: html_document
---

```{r}
library(tidyverse)
data <- data.frame(
Dim1 = rnorm(10,0,25),
Dim2 = rnorm(10,0,9))

# This works
data %>% 
ggplot(aes(x= Dim1, y = Dim2, color = Dim2)) +
  geom_point()
```

```{r}
# This chunk stalls, also does not generate an output file
data %>% 
ggplot(aes(x= Dim1, y = Dim2, color = Dim2)) +
  geom_point() +
  scale_color_viridis_c()
```
`````

### Describe the problem in detail

When I try to knit the above document using the "knit" button, the rmarkdown console starts running, finishes the first chunk, but then stalls in the second chunk. It does not produce an error, it simply does not progress. The plot output image is not created in the corresponding folder, and no document is created. 
However, when I use knitr::knit() or rmarkdown::render() on this file, it works fine. I have noticed this with both viridis_c and viridis_d scales, on two different RStudio Server setups, the first time in May. 
I have also tried changing the document output, which does not seem to have an influence. Everything I have tried (changing color scales, removing color scales, removing geoms etc) indicates that this is issue only appears when using viridis scales. I also tried installing the viridis package and using viridis::scale_color_viridis() which leads to the same issue.
Changing the color scale to a non-viridis scale leads to the expected behavior: the document knits in a couple of seconds.

### Describe the behavior you expected

I would have expected that pressing knit, would lead to the creation of an html document in about the same time it takes when i use rmarkdown::render(), which is < 10 seconds. 

### SessionInfo

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.0     purrr_0.3.4     readr_1.3.1     tidyr_1.1.0    
[7] tibble_3.0.1    ggplot2_3.3.1   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0 xfun_0.14        haven_2.3.1      lattice_0.20-40  colorspace_1.4-1
 [6] vctrs_0.3.0      generics_0.0.2   htmltools_0.4.0  yaml_2.2.1       blob_1.2.1      
[11] rlang_0.4.6      pillar_1.4.4     glue_1.4.1       withr_2.2.0      DBI_1.1.0       
[16] dbplyr_1.4.4     modelr_0.1.8     readxl_1.3.1     lifecycle_0.2.0  munsell_0.5.0   
[21] gtable_0.3.0     cellranger_1.1.0 rvest_0.3.5      evaluate_0.14    knitr_1.28.7    
[26] fansi_0.4.1      broom_0.5.6      Rcpp_1.0.4.6     scales_1.1.1     backports_1.1.7 
[31] jsonlite_1.6.1   fs_1.4.1         hms_0.5.3        digest_0.6.25    stringi_1.4.6   
[36] grid_3.6.3       cli_2.0.2        tools_3.6.3      magrittr_1.5     crayon_1.3.4    
[41] pkgconfig_2.0.3  ellipsis_0.3.1   xml2_1.3.2       reprex_0.3.0     lubridate_1.7.8 
[46] assertthat_0.2.1 rmarkdown_2.2    httr_1.4.1       rstudioapi_0.11  R6_2.4.1        
[51] nlme_3.1-144     compiler_3.6.3  
```

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I tried this on two different RStudio Server instances and could not reproduce. 

Have you tried updating to the latest version of all packages?

**Comment by nschan** [comment]
Yes, I have, the only one that was not up-to-date was vctrs, but updating this did not solve the issue. I realized however that it could related to the particular renv snapshot I have restored to install packages. This snapshot was created in may and appears to contain the up-to-date tidyverse (1.3.0), so it is not clear to me why this would happen. The lockfile can be found here https://github.com/nschan/jubilant-barnacle/blob/master/renv.lock I should mention that is environment contains a lot of packages, and installing all of them takes more than one hour.

**Comment by lboller** [comment]
Same issue is happening for me, and I am reproducing using @nschan's reprex. I ran `update.packages` and am not using renv but still running into the same problem.

Here are my system details:

RStudio Edition : Server
RStudio Version : 1.4.601
OS Version      : Ubuntu 20.04 LTS
R Version       : 4.0.0

**Comment by kevinushey** [comment]
Sorry, but I'm still not able to reproduce.

You could try getting a stack trace (via `gdb`) next time the hang occurs. I think you could do something like:

```
sudo gdb -p `pgrep -nx R` -ex backtrace
```

from a separate Terminal to get a trace of what the R session is up to.

**Comment by lboller** [comment]
Here's the output for your suggestion:

```
sudo gdb -p `pgrep -nx R` -ex backtrace
[sudo] password for lb: 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 92024
[New LWP 92033]
[New LWP 92034]
[New LWP 92035]
[New LWP 92036]
[New LWP 92037]
[New LWP 92038]
[New LWP 92039]
[New LWP 92040]
[New LWP 92041]
[New LWP 92042]
[New LWP 92043]
[New LWP 92044]
[New LWP 92045]
[New LWP 92046]
[New LWP 92047]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f2a20def70b in sched_yield () at ../sysdeps/unix/syscall-template.S:78
78      ../sysdeps/unix/syscall-template.S: No such file or directory.
#0  0x00007f2a20def70b in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007f29f4cd19a5 in exec_blas_async_wait () at /usr/lib/x86_64-linux-gnu/liblapack.so.3
#2  0x00007f29f4cd1a7c in exec_blas () at /usr/lib/x86_64-linux-gnu/liblapack.so.3
#3  0x00007f29f4cd02cf in gemm_thread_n () at /usr/lib/x86_64-linux-gnu/liblapack.so.3
#4  0x00007f29f4ce7057 in dgetrs_N_parallel () at /usr/lib/x86_64-linux-gnu/liblapack.so.3
#5  0x00007f29f45a748e in dgesv_ () at /usr/lib/x86_64-linux-gnu/liblapack.so.3
#6  0x00007f29f307f737 in  () at /usr/lib/R/modules//lapack.so
#7  0x00007f29f3082ed6 in  () at /usr/lib/R/modules//lapack.so
#8  0x00007f2a2103706f in  () at /usr/lib/R/lib/libR.so
#9  0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#10 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#11 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#12 0x00007f2a21097fb4 in  () at /usr/lib/R/lib/libR.so
#13 0x00007f2a21098387 in  () at /usr/lib/R/lib/libR.so
#14 0x00007f2a210987b7 in  () at /usr/lib/R/lib/libR.so
#15 0x00007f2a21036e61 in  () at /usr/lib/R/lib/libR.so
#16 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#17 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#18 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#19 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#20 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#21 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#22 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#23 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#24 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#25 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#26 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#27 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#28 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--
#29 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#30 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#31 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#32 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#33 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#34 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#35 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#36 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#37 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#38 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#39 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#40 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#41 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#42 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#43 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#44 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#45 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#46 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#47 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#48 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#49 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#50 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#51 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#52 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#53 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#54 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#55 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#56 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#57 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#58 0x00007f2a210520c8 in Rf_eval () at /usr/lib/R/lib/libR.so
#59 0x00007f2a210482d1 in  () at /usr/lib/R/lib/libR.so
#60 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#61 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#62 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#63 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#64 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#65 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#66 0x00007f2a210520c8 in Rf_eval () at /usr/lib/R/lib/libR.so
#67 0x00007f2a210482d1 in  () at /usr/lib/R/lib/libR.so
#68 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#69 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#70 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#71 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#72 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#73 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#74 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#75 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#76 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#77 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#78 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#79 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#80 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#81 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#82 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#83 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#84 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#85 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#86 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#87 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#88 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#89 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#90 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#91 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--
#92 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#93 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#94 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#95 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#96 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#97 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#98 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#99 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#100 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#101 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#102 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#103 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#104 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#105 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#106 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#107 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#108 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#109 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#110 0x00007f2a210520c8 in Rf_eval () at /usr/lib/R/lib/libR.so
#111 0x00007f2a210482d1 in  () at /usr/lib/R/lib/libR.so
#112 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#113 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#114 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#115 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#116 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#117 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#118 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#119 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#120 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#121 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#122 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#123 0x00007f2a21051d7f in Rf_eval () at /usr/lib/R/lib/libR.so
#124 0x00007f2a21056e37 in  () at /usr/lib/R/lib/libR.so
#125 0x00007f2a21052155 in Rf_eval () at /usr/lib/R/lib/libR.so
#126 0x00007f2a21057d02 in  () at /usr/lib/R/lib/libR.so
#127 0x00007f2a2103706f in  () at /usr/lib/R/lib/libR.so
#128 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#129 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#130 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#131 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#132 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#133 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#134 0x00007f2a21051e6f in Rf_eval () at /usr/lib/R/lib/libR.so
#135 0x00007f2a21058780 in  () at /usr/lib/R/lib/libR.so
#136 0x00007f2a21095cff in  () at /usr/lib/R/lib/libR.so
#137 0x00007f2a21036e61 in  () at /usr/lib/R/lib/libR.so
#138 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#139 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#140 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#141 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#142 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#143 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#144 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#145 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#146 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#147 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#148 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#149 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#150 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#151 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#152 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#153 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#154 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--
#155 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#156 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#157 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#158 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#159 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#160 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#161 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#162 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#163 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#164 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#165 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#166 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#167 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#168 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#169 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#170 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#171 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#172 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#173 0x00007f2a21051d7f in Rf_eval () at /usr/lib/R/lib/libR.so
#174 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#175 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#176 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#177 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#178 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#179 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#180 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#181 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#182 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#183 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#184 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#185 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#186 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#187 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#188 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#189 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#190 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#191 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#192 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#193 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#194 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#195 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#196 0x00007f2a21097fb4 in  () at /usr/lib/R/lib/libR.so
#197 0x00007f2a210983f0 in  () at /usr/lib/R/lib/libR.so
#198 0x00007f2a210987b7 in  () at /usr/lib/R/lib/libR.so
#199 0x00007f2a21036e61 in  () at /usr/lib/R/lib/libR.so
#200 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#201 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#202 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#203 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#204 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#205 0x00007f2a210525ec in  () at /usr/lib/R/lib/libR.so
#206 0x00007f2a21052a98 in  () at /usr/lib/R/lib/libR.so
#207 0x00007f2a2103d6fe in  () at /usr/lib/R/lib/libR.so
#208 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#209 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#210 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#211 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#212 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#213 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#214 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#215 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#216 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#217 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--c
#218 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#219 0x00007f2a2104136e in  () at /usr/lib/R/lib/libR.so
#220 0x00007f2a21051b58 in Rf_eval () at /usr/lib/R/lib/libR.so
#221 0x00007f2a21053a1f in  () at /usr/lib/R/lib/libR.so
#222 0x00007f2a21054912 in Rf_applyClosure () at /usr/lib/R/lib/libR.so
#223 0x00007f2a21051d7f in Rf_eval () at /usr/lib/R/lib/libR.so
#224 0x00007f2a21085c42 in Rf_ReplIteration () at /usr/lib/R/lib/libR.so
#225 0x00007f2a21085fd0 in  () at /usr/lib/R/lib/libR.so
#226 0x00007f2a21086090 in run_Rmainloop () at /usr/lib/R/lib/libR.so
#227 0x000055a05586609f in main ()
#228 0x00007f2a20d110b3 in __libc_start_main (main=0x55a055866080 <main>, argc=6, argv=0x7ffd03389658, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd03389648) at ../csu/libc-start.c:308
#229 0x000055a0558660de in _start ()
(gdb) c
Continuing.
```

**Comment by kevinushey** [comment]
Thanks! I suspect this is caused by the use of a parallel OpenBLAS. See also:

https://github.com/xianyi/OpenBLAS/issues/937
https://github.com/numpy/numpy/issues/11202

I'd recommend using a single-threaded BLAS, or (perhaps) filing an issue upstream if you can isolate the issue further.

**Comment by kevinushey** [comment]
In case it's helpful, please see https://csantill.github.io/RPerformanceWBLAS/ for a guide on how to configure R to use different BLAS implementations.

**Comment by lboller** [comment]
Thanks!
