### ISSUE TITLE
ensure that quarto projects in subdirectories of rstudio projects can be served/previewed

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#9643]
For example: https://github.com/dspatterns/dspatterns/tree/main/quarto-book

**Comment by jjallaire** [comment]
We currently get this error when doing a Render even though the book is being served in the viewer pane via `quarto_serve()`:

```
ERROR: Error: Target file 01-starting-with-projects.Rmd is in a book project (preview this file using quarto serve).
    at preview (file:///Users/jjallaire/quarto/quarto-cli/src/command/preview/preview.ts:64:11)
    at async Command.fn (file:///Users/jjallaire/quarto/quarto-cli/src/command/preview/cmd.ts:110:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///Users/jjallaire/quarto/quarto-cli/src/quarto.ts:58:3)
    at async file:///Users/jjallaire/quarto/quarto-cli/src/quarto.ts:76:5
```

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/rstudio/commit/afe9cb4e8302d72d49b9b416165b8362bb5a899f

@apreshill This error message will no longer occur for your scenario (it will just render the file w/o any preview being triggered). This means that the `quarto::quarto_serve("quarto-book")` works.

Currently the IDE Quarto build tools kick in when the `_quarto.yml` file is in the same directory as the RStudio project file so this is the recommended configuration (we wiill look at making this more flexible in future IDE releases).

**Comment by R-Hannibal** [comment]
Moving this to Elsbeth Geranium for verification (code is in Ghost Orchid).
